### ISSUE TITLE
SQL Injection Risk

### ISSUE THREAD

**Issue by peterrupa** [mikeserato/Review-Helpfulness-Classifier#1]
At controllers/reviews.js

    db.query("SELECT * FROM degree WHERE degree_id='"+req.params.id+"'", function (err, rows) {
        if(err) return(err);
        if(rows.length === 0)
            res.send(404, {message: 'Degree program not found.'});
        else res.send(rows[0]);
    });

It concatenates `req.params.id` without escaping so you might get injected here.

**Comment by mikeserato** [comment]
Thanks Papa P! :*
